filenames:
  data: a
  trained_model: b
general:
  gestures:
  - a
  - b
  - c
  num_reps: 1
  num_sensors: 1
  num_sets: 1
hyperparams:
  batch_size: 1
  learning_capacity: 1
  lr: 1.0
  num_epochs: 1
