filenames:
  data: test
  trained_model: test
general:
  gestures:
  - one
  - two
  - three
  num_reps: 500
  num_sensors: 7
  num_sets: 1
hyperparams:
  batch_size: 128
  learning_capacity: 32
  lr: 0.0001
  num_epochs: 500
