filenames:
  data: example_dataset
  trained_model: example_model
general:
  gestures:
  - rest
  - flexion
  - extension
  - adduction
  - abduction
  - rotation
  num_reps: 500
  num_sensors: 10
  num_sets: 1
hyperparams:
  batch_size: 128
  learning_capacity: 32
  lr: 0.0001
  num_epochs: 500
