# Paths to particular files
filepaths:
  data: data/example_dataset.csv
  trained_model: trained_models/example_model.pth

# Hyperparameters for machine learning
hyperparams:
  num_epochs: 500
  lr: 0.00001
  batch_size: 128
  learning_capacity: 32

# General parameters
general: 
  num_sensors: 7
  gestures:
    - rock
    - paper
    - scissors
  num_reps: 500
  num_sets: 3