filenames:
  data: '1'
  trained_model: '1'
general:
  gestures:
  - '1'
  - '2'
  - '3'
  num_reps: 123
  num_sensors: 7
  num_sets: 1
hyperparams:
  batch_size: 32
  learning_capacity: 32
  lr: 0.0001
  num_epochs: 369
