filenames:
  data: example_dataset
  trained_model: example_model
general:
  gestures:
  - rock
  - paper
  - scissors
  num_reps: 500
  num_sensors: 7
  num_sets: 2
hyperparams:
  batch_size: 128
  learning_capacity: 32
  lr: 0.0001
  num_epochs: 500
