filenames:
  data: example_dataset
  trained_model: example_model
general:
  gestures:
  - rock
  - paper
  - scissors
  num_reps: 400
  num_sensors: 7
  num_sets: 1
hyperparams:
  batch_size: 128
  learning_capacity: 32
  lr: 1.0e-05
  num_epochs: 500
